webpackJsonp(["home.module"],{

/***/ "./src/app/home/home-agent/home-agent.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/home/home-agent/home-agent.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.Router_1 = router_1.Router;
exports.UrlSerializer_3 = router_1.UrlSerializer;
exports.ChildrenOutletContexts_4 = router_1.ChildrenOutletContexts;
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.Location_5 = common_1.Location;
exports.LocationStrategy_6 = common_1.LocationStrategy;
exports.DOCUMENT_14 = common_1.DOCUMENT;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.Injector_7 = core_1.Injector;
exports.NgModuleFactoryLoader_8 = core_1.NgModuleFactoryLoader;
exports.Compiler_9 = core_1.Compiler;
exports.Inject_12 = core_1.Inject;
exports.ɵa_13 = core_1.ɵa;
exports.InjectionToken_15 = core_1.InjectionToken;
var cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
exports.CookieService_11 = cookie_service_1.CookieService;
var i0 = __webpack_require__("./src/app/home/home-agent/home-agent.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/home/home-agent/home-agent.component.ts");
var i3 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var i4 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
var styles_HomeAgentComponent = [i0.styles];
var RenderType_HomeAgentComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeAgentComponent, data: {} });
exports.RenderType_HomeAgentComponent = RenderType_HomeAgentComponent;
function View_HomeAgentComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\n  home-agent works!\n"])), (_l()(), i1.ɵted(-1, null, ["\n"]))], null, null); }
exports.View_HomeAgentComponent_0 = View_HomeAgentComponent_0;
function View_HomeAgentComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home-agent", [], null, null, null, View_HomeAgentComponent_0, RenderType_HomeAgentComponent)), i1.ɵdid(1, 114688, null, 0, i2.HomeAgentComponent, [i3.Router, i4.CookieService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeAgentComponent_Host_0 = View_HomeAgentComponent_Host_0;
var HomeAgentComponentNgFactory = i1.ɵccf("app-home-agent", i2.HomeAgentComponent, View_HomeAgentComponent_Host_0, {}, {}, []);
exports.HomeAgentComponentNgFactory = HomeAgentComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home-agent/home-agent.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var ngx_cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/index.js");
var HomeAgentComponent = /** @class */ (function () {
    function HomeAgentComponent(router, cookie) {
        this.router = router;
        this.cookie = cookie;
    }
    HomeAgentComponent.prototype.ngOnInit = function () {
        if (this.cookie.get('type') !== 'booking_agent') {
            this.router.navigate(['/home']);
        }
    };
    return HomeAgentComponent;
}());
exports.HomeAgentComponent = HomeAgentComponent;


/***/ }),

/***/ "./src/app/home/home-customer/home-customer.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/home/home-customer/home-customer.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.Router_1 = router_1.Router;
exports.UrlSerializer_3 = router_1.UrlSerializer;
exports.ChildrenOutletContexts_4 = router_1.ChildrenOutletContexts;
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.Location_5 = common_1.Location;
exports.LocationStrategy_6 = common_1.LocationStrategy;
exports.DOCUMENT_14 = common_1.DOCUMENT;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.Injector_7 = core_1.Injector;
exports.NgModuleFactoryLoader_8 = core_1.NgModuleFactoryLoader;
exports.Compiler_9 = core_1.Compiler;
exports.Inject_12 = core_1.Inject;
exports.ɵa_13 = core_1.ɵa;
exports.InjectionToken_15 = core_1.InjectionToken;
var cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
exports.CookieService_11 = cookie_service_1.CookieService;
var i0 = __webpack_require__("./src/app/home/home-customer/home-customer.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/home/home-customer/home-customer.component.ts");
var i3 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var i4 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
var styles_HomeCustomerComponent = [i0.styles];
var RenderType_HomeCustomerComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeCustomerComponent, data: {} });
exports.RenderType_HomeCustomerComponent = RenderType_HomeCustomerComponent;
function View_HomeCustomerComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\n  home-customer works!\n"])), (_l()(), i1.ɵted(-1, null, ["\n"]))], null, null); }
exports.View_HomeCustomerComponent_0 = View_HomeCustomerComponent_0;
function View_HomeCustomerComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home-customer", [], null, null, null, View_HomeCustomerComponent_0, RenderType_HomeCustomerComponent)), i1.ɵdid(1, 114688, null, 0, i2.HomeCustomerComponent, [i3.Router, i4.CookieService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeCustomerComponent_Host_0 = View_HomeCustomerComponent_Host_0;
var HomeCustomerComponentNgFactory = i1.ɵccf("app-home-customer", i2.HomeCustomerComponent, View_HomeCustomerComponent_Host_0, {}, {}, []);
exports.HomeCustomerComponentNgFactory = HomeCustomerComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home-customer/home-customer.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var ngx_cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/index.js");
var HomeCustomerComponent = /** @class */ (function () {
    function HomeCustomerComponent(router, cookie) {
        this.router = router;
        this.cookie = cookie;
    }
    HomeCustomerComponent.prototype.ngOnInit = function () {
        if (this.cookie.get('type') !== 'customer') {
            this.router.navigate(['/home']);
        }
    };
    return HomeCustomerComponent;
}());
exports.HomeCustomerComponent = HomeCustomerComponent;


/***/ }),

/***/ "./src/app/home/home-routing.module.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var home_component_1 = __webpack_require__("./src/app/home/home/home.component.ts");
var home_staff_component_1 = __webpack_require__("./src/app/home/home-staff/home-staff.component.ts");
var home_customer_component_1 = __webpack_require__("./src/app/home/home-customer/home-customer.component.ts");
var home_agent_component_1 = __webpack_require__("./src/app/home/home-agent/home-agent.component.ts");
var routes = [
    { path: '', component: home_component_1.HomeComponent },
    { path: 'agent', component: home_agent_component_1.HomeAgentComponent },
    { path: 'customer', component: home_customer_component_1.HomeCustomerComponent },
    { path: 'staff', component: home_staff_component_1.HomeStaffComponent }
];
var HomeRoutingModule = /** @class */ (function () {
    function HomeRoutingModule() {
    }
    return HomeRoutingModule;
}());
exports.HomeRoutingModule = HomeRoutingModule;


/***/ }),

/***/ "./src/app/home/home-staff/home-staff.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/home/home-staff/home-staff.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.Router_1 = router_1.Router;
exports.UrlSerializer_3 = router_1.UrlSerializer;
exports.ChildrenOutletContexts_4 = router_1.ChildrenOutletContexts;
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.Location_5 = common_1.Location;
exports.LocationStrategy_6 = common_1.LocationStrategy;
exports.DOCUMENT_14 = common_1.DOCUMENT;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.Injector_7 = core_1.Injector;
exports.NgModuleFactoryLoader_8 = core_1.NgModuleFactoryLoader;
exports.Compiler_9 = core_1.Compiler;
exports.Inject_12 = core_1.Inject;
exports.ɵa_13 = core_1.ɵa;
exports.InjectionToken_15 = core_1.InjectionToken;
var cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
exports.CookieService_11 = cookie_service_1.CookieService;
var i0 = __webpack_require__("./src/app/home/home-staff/home-staff.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/home/home-staff/home-staff.component.ts");
var i3 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var i4 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
var styles_HomeStaffComponent = [i0.styles];
var RenderType_HomeStaffComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeStaffComponent, data: {} });
exports.RenderType_HomeStaffComponent = RenderType_HomeStaffComponent;
function View_HomeStaffComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\n  home-staff works!\n"])), (_l()(), i1.ɵted(-1, null, ["\n"]))], null, null); }
exports.View_HomeStaffComponent_0 = View_HomeStaffComponent_0;
function View_HomeStaffComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home-staff", [], null, null, null, View_HomeStaffComponent_0, RenderType_HomeStaffComponent)), i1.ɵdid(1, 114688, null, 0, i2.HomeStaffComponent, [i3.Router, i4.CookieService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeStaffComponent_Host_0 = View_HomeStaffComponent_Host_0;
var HomeStaffComponentNgFactory = i1.ɵccf("app-home-staff", i2.HomeStaffComponent, View_HomeStaffComponent_Host_0, {}, {}, []);
exports.HomeStaffComponentNgFactory = HomeStaffComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home-staff/home-staff.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var ngx_cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/index.js");
var HomeStaffComponent = /** @class */ (function () {
    function HomeStaffComponent(router, cookie) {
        this.router = router;
        this.cookie = cookie;
    }
    HomeStaffComponent.prototype.ngOnInit = function () {
        if (this.cookie.get('type') !== 'airline_staff') {
            this.router.navigate(['/home']);
        }
    };
    return HomeStaffComponent;
}());
exports.HomeStaffComponent = HomeStaffComponent;


/***/ }),

/***/ "./src/app/home/home.module.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.NgLocalization_9 = common_1.NgLocalization;
exports.NgLocaleLocalization_10 = common_1.NgLocaleLocalization;
exports.ɵa_12 = common_1.ɵa;
exports.CommonModule_13 = common_1.CommonModule;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.LOCALE_ID_11 = core_1.LOCALE_ID;
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.ROUTES_14 = router_1.ROUTES;
exports.RouterModule_18 = router_1.RouterModule;
exports.ɵa_19 = router_1.ɵa;
exports.Router_20 = router_1.Router;
var forms_1 = __webpack_require__("./node_modules/@angular/forms/esm5/forms.js");
exports.ɵi_16 = forms_1.ɵi;
exports.FormsModule_17 = forms_1.FormsModule;
exports.ɵba_21 = forms_1.ɵba;
var i0 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i1 = __webpack_require__("./src/app/home/home.module.ts");
var i2 = __webpack_require__("./src/app/home/home/home.component.ngfactory.js");
var i3 = __webpack_require__("./src/app/home/home-agent/home-agent.component.ngfactory.js");
var i4 = __webpack_require__("./src/app/home/home-customer/home-customer.component.ngfactory.js");
var i5 = __webpack_require__("./src/app/home/home-staff/home-staff.component.ngfactory.js");
var i6 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
var i7 = __webpack_require__("./node_modules/@angular/forms/esm5/forms.js");
var i8 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var i9 = __webpack_require__("./src/app/home/home-routing.module.ts");
var i10 = __webpack_require__("./src/app/home/home/home.component.ts");
var i11 = __webpack_require__("./src/app/home/home-agent/home-agent.component.ts");
var i12 = __webpack_require__("./src/app/home/home-customer/home-customer.component.ts");
var i13 = __webpack_require__("./src/app/home/home-staff/home-staff.component.ts");
var HomeModuleNgFactory = i0.ɵcmf(i1.HomeModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i2.HomeComponentNgFactory, i3.HomeAgentComponentNgFactory, i4.HomeCustomerComponentNgFactory, i5.HomeStaffComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608, i6.NgLocalization, i6.NgLocaleLocalization, [i0.LOCALE_ID, [2, i6.ɵa]]), i0.ɵmpd(4608, i7.ɵi, i7.ɵi, []), i0.ɵmpd(512, i6.CommonModule, i6.CommonModule, []), i0.ɵmpd(512, i8.RouterModule, i8.RouterModule, [[2, i8.ɵa], [2, i8.Router]]), i0.ɵmpd(512, i9.HomeRoutingModule, i9.HomeRoutingModule, []), i0.ɵmpd(512, i7.ɵba, i7.ɵba, []), i0.ɵmpd(512, i7.FormsModule, i7.FormsModule, []), i0.ɵmpd(512, i1.HomeModule, i1.HomeModule, []), i0.ɵmpd(1024, i8.ROUTES, function () { return [[{ path: "", component: i10.HomeComponent }, { path: "agent", component: i11.HomeAgentComponent }, { path: "customer", component: i12.HomeCustomerComponent }, { path: "staff", component: i13.HomeStaffComponent }]]; }, [])]); });
exports.HomeModuleNgFactory = HomeModuleNgFactory;


/***/ }),

/***/ "./src/app/home/home.module.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var HomeModule = /** @class */ (function () {
    function HomeModule() {
    }
    return HomeModule;
}());
exports.HomeModule = HomeModule;


/***/ }),

/***/ "./src/app/home/home/home.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/home/home/home.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.Router_1 = router_1.Router;
exports.UrlSerializer_3 = router_1.UrlSerializer;
exports.ChildrenOutletContexts_4 = router_1.ChildrenOutletContexts;
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.Location_5 = common_1.Location;
exports.LocationStrategy_6 = common_1.LocationStrategy;
exports.DOCUMENT_14 = common_1.DOCUMENT;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.Injector_7 = core_1.Injector;
exports.NgModuleFactoryLoader_8 = core_1.NgModuleFactoryLoader;
exports.Compiler_9 = core_1.Compiler;
exports.Inject_12 = core_1.Inject;
exports.ɵa_13 = core_1.ɵa;
exports.InjectionToken_15 = core_1.InjectionToken;
var cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
exports.CookieService_11 = cookie_service_1.CookieService;
var i0 = __webpack_require__("./src/app/home/home/home.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/home/home/home.component.ts");
var i3 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var i4 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
var styles_HomeComponent = [i0.styles];
var RenderType_HomeComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeComponent, data: {} });
exports.RenderType_HomeComponent = RenderType_HomeComponent;
function View_HomeComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, "div", [["class", "main"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\n  "])), (_l()(), i1.ɵted(-1, null, ["\n"]))], null, null); }
exports.View_HomeComponent_0 = View_HomeComponent_0;
function View_HomeComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home", [], null, null, null, View_HomeComponent_0, RenderType_HomeComponent)), i1.ɵdid(1, 114688, null, 0, i2.HomeComponent, [i3.Router, i4.CookieService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeComponent_Host_0 = View_HomeComponent_Host_0;
var HomeComponentNgFactory = i1.ɵccf("app-home", i2.HomeComponent, View_HomeComponent_Host_0, {}, {}, []);
exports.HomeComponentNgFactory = HomeComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home/home.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var ngx_cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/index.js");
var HomeComponent = /** @class */ (function () {
    function HomeComponent(router, cookieService) {
        this.router = router;
        this.cookieService = cookieService;
    }
    HomeComponent.prototype.ngOnInit = function () {
        var type = this.cookieService.get('type');
        if (type === 'customer') {
            this.router.navigate(['/home/customer']);
        }
        else if (type === 'airline_staff') {
            this.router.navigate(['/home/staff']);
        }
        else if (type === 'booking_agent') {
            this.router.navigate(['/home/agent']);
        }
    };
    return HomeComponent;
}());
exports.HomeComponent = HomeComponent;


/***/ })

});
//# sourceMappingURL=home.module.chunk.js.map