webpackJsonp(["purchase.module"],{

/***/ "./src/app/purchase/agent/agent.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/purchase/agent/agent.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__("./src/app/purchase/agent/agent.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/purchase/agent/agent.component.ts");
var styles_AgentComponent = [i0.styles];
var RenderType_AgentComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AgentComponent, data: {} });
exports.RenderType_AgentComponent = RenderType_AgentComponent;
function View_AgentComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\n  agent works!\n"])), (_l()(), i1.ɵted(-1, null, ["\n"]))], null, null); }
exports.View_AgentComponent_0 = View_AgentComponent_0;
function View_AgentComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-agent", [], null, null, null, View_AgentComponent_0, RenderType_AgentComponent)), i1.ɵdid(1, 114688, null, 0, i2.AgentComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AgentComponent_Host_0 = View_AgentComponent_Host_0;
var AgentComponentNgFactory = i1.ɵccf("app-agent", i2.AgentComponent, View_AgentComponent_Host_0, {}, {}, []);
exports.AgentComponentNgFactory = AgentComponentNgFactory;


/***/ }),

/***/ "./src/app/purchase/agent/agent.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AgentComponent = /** @class */ (function () {
    function AgentComponent() {
    }
    AgentComponent.prototype.ngOnInit = function () {
    };
    return AgentComponent;
}());
exports.AgentComponent = AgentComponent;


/***/ }),

/***/ "./src/app/purchase/customer/customer.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/purchase/customer/customer.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__("./src/app/purchase/customer/customer.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/purchase/customer/customer.component.ts");
var styles_CustomerComponent = [i0.styles];
var RenderType_CustomerComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_CustomerComponent, data: {} });
exports.RenderType_CustomerComponent = RenderType_CustomerComponent;
function View_CustomerComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\n  customer works!\n"])), (_l()(), i1.ɵted(-1, null, ["\n"]))], null, null); }
exports.View_CustomerComponent_0 = View_CustomerComponent_0;
function View_CustomerComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-customer", [], null, null, null, View_CustomerComponent_0, RenderType_CustomerComponent)), i1.ɵdid(1, 114688, null, 0, i2.CustomerComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_CustomerComponent_Host_0 = View_CustomerComponent_Host_0;
var CustomerComponentNgFactory = i1.ɵccf("app-customer", i2.CustomerComponent, View_CustomerComponent_Host_0, {}, {}, []);
exports.CustomerComponentNgFactory = CustomerComponentNgFactory;


/***/ }),

/***/ "./src/app/purchase/customer/customer.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var CustomerComponent = /** @class */ (function () {
    function CustomerComponent() {
    }
    CustomerComponent.prototype.ngOnInit = function () {
    };
    return CustomerComponent;
}());
exports.CustomerComponent = CustomerComponent;


/***/ }),

/***/ "./src/app/purchase/purchase-routing.module.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var redirect_component_1 = __webpack_require__("./src/app/purchase/redirect/redirect.component.ts");
var customer_component_1 = __webpack_require__("./src/app/purchase/customer/customer.component.ts");
var agent_component_1 = __webpack_require__("./src/app/purchase/agent/agent.component.ts");
var routes = [
    { path: '', component: redirect_component_1.RedirectComponent },
    { path: 'customer', component: customer_component_1.CustomerComponent },
    { path: 'agent', component: agent_component_1.AgentComponent }
];
var PurchaseRoutingModule = /** @class */ (function () {
    function PurchaseRoutingModule() {
    }
    return PurchaseRoutingModule;
}());
exports.PurchaseRoutingModule = PurchaseRoutingModule;


/***/ }),

/***/ "./src/app/purchase/purchase.module.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.NgLocalization_7 = common_1.NgLocalization;
exports.NgLocaleLocalization_8 = common_1.NgLocaleLocalization;
exports.ɵa_10 = common_1.ɵa;
exports.CommonModule_11 = common_1.CommonModule;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.LOCALE_ID_9 = core_1.LOCALE_ID;
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.ROUTES_12 = router_1.ROUTES;
exports.RouterModule_14 = router_1.RouterModule;
exports.ɵa_15 = router_1.ɵa;
exports.Router_16 = router_1.Router;
var i0 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i1 = __webpack_require__("./src/app/purchase/purchase.module.ts");
var i2 = __webpack_require__("./src/app/purchase/redirect/redirect.component.ngfactory.js");
var i3 = __webpack_require__("./src/app/purchase/customer/customer.component.ngfactory.js");
var i4 = __webpack_require__("./src/app/purchase/agent/agent.component.ngfactory.js");
var i5 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
var i6 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var i7 = __webpack_require__("./src/app/purchase/purchase-routing.module.ts");
var i8 = __webpack_require__("./src/app/purchase/redirect/redirect.component.ts");
var i9 = __webpack_require__("./src/app/purchase/customer/customer.component.ts");
var i10 = __webpack_require__("./src/app/purchase/agent/agent.component.ts");
var PurchaseModuleNgFactory = i0.ɵcmf(i1.PurchaseModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i2.RedirectComponentNgFactory, i3.CustomerComponentNgFactory, i4.AgentComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608, i5.NgLocalization, i5.NgLocaleLocalization, [i0.LOCALE_ID, [2, i5.ɵa]]), i0.ɵmpd(512, i5.CommonModule, i5.CommonModule, []), i0.ɵmpd(512, i6.RouterModule, i6.RouterModule, [[2, i6.ɵa], [2, i6.Router]]), i0.ɵmpd(512, i7.PurchaseRoutingModule, i7.PurchaseRoutingModule, []), i0.ɵmpd(512, i1.PurchaseModule, i1.PurchaseModule, []), i0.ɵmpd(1024, i6.ROUTES, function () { return [[{ path: "", component: i8.RedirectComponent }, { path: "customer", component: i9.CustomerComponent }, { path: "agent", component: i10.AgentComponent }]]; }, [])]); });
exports.PurchaseModuleNgFactory = PurchaseModuleNgFactory;


/***/ }),

/***/ "./src/app/purchase/purchase.module.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var PurchaseModule = /** @class */ (function () {
    function PurchaseModule() {
    }
    return PurchaseModule;
}());
exports.PurchaseModule = PurchaseModule;


/***/ }),

/***/ "./src/app/purchase/redirect/redirect.component.css.shim.ngstyle.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [""];
exports.styles = styles;


/***/ }),

/***/ "./src/app/purchase/redirect/redirect.component.ngfactory.js":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
exports.CookieService_1 = cookie_service_1.CookieService;
var core_1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
exports.Inject_2 = core_1.Inject;
exports.ɵa_3 = core_1.ɵa;
exports.InjectionToken_5 = core_1.InjectionToken;
exports.Injector_12 = core_1.Injector;
exports.NgModuleFactoryLoader_13 = core_1.NgModuleFactoryLoader;
exports.Compiler_14 = core_1.Compiler;
var common_1 = __webpack_require__("./node_modules/@angular/common/esm5/common.js");
exports.DOCUMENT_4 = common_1.DOCUMENT;
exports.Location_10 = common_1.Location;
exports.LocationStrategy_11 = common_1.LocationStrategy;
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
exports.Router_6 = router_1.Router;
exports.UrlSerializer_8 = router_1.UrlSerializer;
exports.ChildrenOutletContexts_9 = router_1.ChildrenOutletContexts;
var i0 = __webpack_require__("./src/app/purchase/redirect/redirect.component.css.shim.ngstyle.js");
var i1 = __webpack_require__("./node_modules/@angular/core/esm5/core.js");
var i2 = __webpack_require__("./src/app/purchase/redirect/redirect.component.ts");
var i3 = __webpack_require__("./node_modules/ngx-cookie-service/cookie-service/cookie.service.js");
var i4 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var styles_RedirectComponent = [i0.styles];
var RenderType_RedirectComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_RedirectComponent, data: {} });
exports.RenderType_RedirectComponent = RenderType_RedirectComponent;
function View_RedirectComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "div", [["class", "main"]], null, null, null, null, null)), (_l()(), i1.ɵted(1, null, ["\n  ", "\n"]))], null, function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.message; _ck(_v, 1, 0, currVal_0); }); }
exports.View_RedirectComponent_0 = View_RedirectComponent_0;
function View_RedirectComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-redirect", [], null, null, null, View_RedirectComponent_0, RenderType_RedirectComponent)), i1.ɵdid(1, 114688, null, 0, i2.RedirectComponent, [i3.CookieService, i4.Router], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_RedirectComponent_Host_0 = View_RedirectComponent_Host_0;
var RedirectComponentNgFactory = i1.ɵccf("app-redirect", i2.RedirectComponent, View_RedirectComponent_Host_0, {}, {}, []);
exports.RedirectComponentNgFactory = RedirectComponentNgFactory;


/***/ }),

/***/ "./src/app/purchase/redirect/redirect.component.ts":
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var ngx_cookie_service_1 = __webpack_require__("./node_modules/ngx-cookie-service/index.js");
var router_1 = __webpack_require__("./node_modules/@angular/router/esm5/router.js");
var RedirectComponent = /** @class */ (function () {
    function RedirectComponent(cookie, router) {
        this.cookie = cookie;
        this.router = router;
        this.message = '';
    }
    RedirectComponent.prototype.ngOnInit = function () {
        var _this = this;
        var type = this.cookie.get('type');
        if (type === 'customer') {
            this.router.navigate(['/buy/customer']);
        }
        else if (type === 'booking_agent') {
            this.router.navigate(['/buy/agent']);
        }
        else if (type === 'airline_staff') {
            this.message = 'You cannot buy tickets as an airline staff, redirecting you to the home page ...';
            setTimeout(function () {
                _this.router.navigate(['home']);
            }, 2000);
        }
        else {
            this.message = 'You are not logged in yet, redirecting you to the loggin page ...';
            setTimeout(function () {
                _this.router.navigate(['login']);
            }, 2000);
        }
    };
    return RedirectComponent;
}());
exports.RedirectComponent = RedirectComponent;


/***/ })

});
//# sourceMappingURL=purchase.module.chunk.js.map